### ISSUE TITLE
Start every chapter with a quoted tweet?

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#10]

**Comment by oscarbaruffa** [comment]
What sort of tweets are you thinking of?

**Comment by veerlevanson** [comment]
We could start every chapter by quoting a tweet that is relevant to the content of the chapter. Like books sometimes have a quote at the start of every chapter. We would have to look for tweets that would go well with the chapters. Just an idea, I don't know how hard it is to find suitable tweets :)

**Comment by oscarbaruffa** [comment]
I see, yes that's a nice touch. We can add as we go but if we don't have
them all, still consider the book "ready"

**Comment by veerlevanson** [comment]
I think we've added enough tweets to the book as is, we don't have to switch to this format.
