### ISSUE TITLE
Add chapter on why Twitter is useful for R programmers

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#15]
The book starts directly with the "how", but we should add a chapter that goes into the "why". Makes sense to have that as the first chapter?

**Comment by oscarbaruffa** [comment]
Yes good idea. Feel free to start or I'll pick it up :)

**Comment by veerlevanson** [comment]
I just created chapter 13: What you can get out of Twitter. I'd like to move it to the front of the book. Is there a way to do this without manually changing every chapter number?

**Comment by oscarbaruffa** [comment]
The book knits alphabetically/numerically, so change it to chapter 1 (I
think) or whatever makes it ordered where you want it. Index always comes
first.

If the chapter number and file number get out of sync, that's ok

**Comment by veerlevanson** [comment]
Chapter was moved to the front of the book
