### ISSUE TITLE
CSS for blockquotes (quoted tweets)

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#16]
I've added CSS code for styling quoted tweets, but they seem to show up differently in different browsers. The way Chrome shows them looks better. Chrome seems to override the CSS and it includes the images (Firefox doesn't). @oscarbaruffa can you check what this looks like on your end?
 

Screenshot Chrome:
![Screenshot Chrome](https://user-images.githubusercontent.com/7224147/75094587-ee4c9480-558c-11ea-8338-c7112ca91f54.png)

Screenshot Firefox:
![Screenshot Firefox](https://user-images.githubusercontent.com/7224147/75094589-f573a280-558c-11ea-99d5-de2423f7b0e5.png)

**Comment by oscarbaruffa** [comment]
My firefox shows up fine. What your firefox does, it was my side shows when the book is first opened by the Rstudio default browser, but if I then open it in either firefox or chrome, it looks fine

**Comment by oscarbaruffa** [comment]
@veerlevanson  could you check if this is still happening?

**Comment by oscarbaruffa** [comment]
I can recreate the issue in Firefox incognito mode but in normal mode it still works ok

**Comment by oscarbaruffa** [comment]
I've tested this on another devoces Firefox and seems to be working fine now. Firefox does take longer to load images, maybe it was that?
