### ISSUE TITLE
Ask permission of people whose tweets we've included

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#17]
Would be the proper thing to do. We might have to look for alternative tweets to quote if people don't want their tweets included or if it takes too long to get an answer.

**Comment by oscarbaruffa** [comment]
Yes good idea

**Comment by oscarbaruffa** [comment]
Ive asked everyone. So far so good. Will record who all said yes

**Comment by oscarbaruffa** [comment]
Yes:
Benjamin wolf 
Joshua parry
Nicole Radziwill
Allison Horst
Thomas Mocke
Drew Conway
Sharla Gelfand


Still awaiting:
Kara Woo
David Keyes
Jesse Mostipak
Laura Ellis
Michael Driscoll
RNIB

TheSmartJokes
Emoji mashup bot
Utrecht weather

**Comment by oscarbaruffa** [comment]
We've got okays from most of the accounts (about 90% I'd say) and otherwise no response and/or no objections. 

I'll close this out for now but feel free to re-open it if you'd like us to follow up with each account.
