### ISSUE TITLE
Ads How to ask for help

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/Book-Twitter-for-R#19]
There was a tweet thread somewhere describing good steps to take when asking for help on rstats. Will find it or add what I can remember

**Comment by veerlevanson** [comment]
Do you mean this tweet? https://twitter.com/sctyner/status/1206986161434058752

**Comment by oscarbaruffa** [comment]
Wow, that's exactly it!

**Comment by veerlevanson** [comment]
Took me some time to find it, but I knew I had seen it somewhere!
