### ISSUE TITLE
@WeAreRLadies RoCur account

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#20]
I'd like to add a paragraph about this somewhere in the book. Not sure where yet :)
What it is and how to sign up

**Comment by oscarbaruffa** [comment]
Great idea. I think that could go with the current chapter 7 "extra info"
and we could maybe call the chapter "diving deeper in twitter" or something
like that. We should move it more towards the end, maybe before the Authors
section.

The "thanks" bit of text in the Thanks chapter can be move to the Authors
chapter and the Further reading could be moved to this new Dove Deeper
section. Thanks chapter can be deleted.

**Comment by oscarbaruffa** [comment]
this can be in the new section "Diving deeper into R and Twitter", but move it if you find soemwhere better

**Comment by veerlevanson** [comment]
I like the new chapter name and I think this is the right place for it
