### ISSUE TITLE
Account that automatically retweets if you use #rstats hashtag

### ISSUE THREAD

**Issue by veerlevanson** [oscarbaruffa/Book-Twitter-for-R#21]
Bot account?

**Comment by oscarbaruffa** [comment]
Which one is it? There's one that retweets everything that I don't like
because it was retweeting a lot of pointless arguments between base r and
tidyverse which I didn't think was that great especially for newbies

**Comment by veerlevanson** [comment]
This one: https://twitter.com/rstatstweet
Worth mentioning that if you use the #rstats hashtag it will get retweeted by this account

**Comment by oscarbaruffa** [comment]
Ah yes.

**Comment by veerlevanson** [comment]
Added this paragraph to chapter 4 about #rstats hashtag
