### ISSUE TITLE
Reference to TidyTuesday incomplete

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/Book-Twitter-for-R#23]
![Screenshot_20200229_124249_org mozilla firefox](https://user-images.githubusercontent.com/16580713/75606864-72ed6480-5af1-11ea-832d-4181b4815a1f.jpg)

On index

**Comment by oscarbaruffa** [comment]
@veerlevanson i cant recall who added this - is this somethign you want to expand on?

**Comment by veerlevanson** [comment]
I wrote the original text in index.Rmd, you filed the issue, I'll expand the text and close the issue :)

**Comment by oscarbaruffa** [comment]
But this is the text still showing?

"1.1.3 Learn from each other
Tidy Tuesday (more about this later in the book) Ask questions

Everybody struggles sometimes, and that’s OK. Support network"
