### ISSUE TITLE
Link to rendered book

### ISSUE THREAD

**Issue by hadley** [oscarbaruffa/Book-Twitter-for-R#36]
In the description for the book, i.e. at the top-right here:

<img width="1044" alt="Screenshot 2020-03-05 at 8 07 06 AM" src="https://user-images.githubusercontent.com/4196/75989137-561dac00-5eb8-11ea-98b1-e91d463a7b3e.png">

**Comment by oscarbaruffa** [comment]
Thanks! Didn't know that was possible :)
