### ISSUE TITLE
Submit to rweekly

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/Book-Twitter-for-R#38]

**Comment by maelle** [comment]
Yes! Make a PR on a weekday.

**Comment by oscarbaruffa** [comment]
Cool, ok will do so next week

**Comment by oscarbaruffa** [comment]
> Yes! Make a PR on a weekday.

Ok this took me more than 1 week to get to, but I think I've done it correctly :). I submitted via the one-time link submit page.
