### ISSUE TITLE
Purchase custom domain

### ISSUE THREAD

**Issue by oscarbaruffa** [oscarbaruffa/Book-Twitter-for-R#4]
I want to purchase a custom domain that's a bit easier to communicate and doesn't have my name front and centre :).

**Comment by oscarbaruffa** [comment]
@veerlevanson we cant use the word "twitter" in the domain name, but I was thinking of buying T4Rstats.com or something like that. 

T4r is already taken.

**Comment by veerlevanson** [comment]
T4rstats.com sounds good!

**Comment by oscarbaruffa** [comment]
Purchased
