### ISSUE TITLE
Suggestion: automatic deployment via GitHub Actions

### ISSUE THREAD

**Issue by maelle** [oscarbaruffa/Book-Twitter-for-R#40]
See e.g. https://www.hvitfeldt.me/blog/bookdown-netlify-github-actions/

The idea is that when you merge a PR editing an Rmd the book would be updated without your doing anything. You'd need a DESCRIPTION file to track dependencies.

I've added similar workflows to a few bookdown repos recently e.g.https://github.com/ropensci-org/blog-guidance so would be happy to answer any question.

**Comment by oscarbaruffa** [comment]
We've kind-of got this in that Netlify auto deploys when we upload htmls to
the _book folder

**Comment by maelle** [comment]
Right but you still need to render the book to html yourself. 🙂

**Comment by oscarbaruffa** [comment]
Yes indeed :)

**Comment by oscarbaruffa** [comment]
@maelle  I'm a bit nervous to try this on this book now. Although we do need to create the HTMLs and then upload them, it is working ok and not a big hassle to do. I do really like the idea though, and I'll try it out on my next book and if I get it working, will do it here too. Of course if @veerlevanson want's to have a go, she can :)
